# GitHub Pages Configuration for tiation-terminal-workflows
# Dark Neon Theme with Cyan Gradient Flares

title: "tiation terminal workflows"
description: "Enterprise-grade solution with professional documentation and dark neon theme"
baseurl: "/tiation-terminal-workflows"
url: "https://tiaastor.github.io"

# Theme Configuration
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

# SEO and Social
author:
  name: "Tia Astor"
  email: "tia@tiation.com"
  github: "TiaAstor"

social:
  github: "TiaAstor"
  twitter: "TiaAstor"

# GitHub Pages Settings
repository: "TiaAstor/tiation-terminal-workflows"
github_username: "TiaAstor"

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "Documentation"
    url: "/docs/"
  - title: "API Reference"
    url: "/api/"
  - title: "GitHub"
    url: "https://github.com/TiaAstor/tiation-terminal-workflows"

# Markdown Settings
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true

# Exclude from processing
exclude:
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README_OLD.md
  - scripts/
  - .git/
  - .github/

# Include
include:
  - .htaccess
  - _pages
  - docs/
  - api/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      author: "Tia Astor"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Tia Astor"
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
      nav: true

# Custom variables
custom:
  theme_color: "#00D9FF"
  accent_color: "#FF0080"
  background_color: "#0A0A0A"
  text_color: "#FFFFFF"
  highlight_color: "#00FF88"
