title: Tiation Terminal Workflows
description: Enterprise-Grade Terminal Automation & Productivity Scripts
url: https://tiation.github.io/tiation-terminal-workflows
baseurl: /tiation-terminal-workflows

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Site settings
author:
  name: Tiation Team
  email: tiatheone@protonmail.com

# GitHub Pages settings
repository: tiation/tiation-terminal-workflows

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
